# -*- coding: utf-8 -*-
"""Teste Stremlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OauodDttx4q17737ue_rDtqtrySI6TWI
"""

import streamlit as st

# escrevendo um título na página
st.title('Minha primeira aplicação :sunglasses:')
