# -*- coding: utf-8 -*-
"""Teste Stremlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OauodDttx4q17737ue_rDtqtrySI6TWI
"""


import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st

# importando os dados
dados = pd.read_csv('/content/estoque.csv')

st.title('Análise de estoque\n')
st.write('Nesse projeto vamos analisar a quantidade de produtos em estoque, por categoria, de uma base de dados de produtos de supermercado')

# Filtro da tabela
checkbox_mostrar_tabela = st.sidebar.checkbox('Mostrar tabela')
if checkbox_mostrar_tabela:
    st.sidebar.markdown('## Filtro para a tabela')

    categorias = list(dados['Categoria'].unique())
    categorias.append('Todas')

    categoria = st.sidebar.selectbox('Selecione a categoria para apresentar na tabela', options=categorias)

    # Aplicando o filtro
    if categoria != 'Todas':
        df_categoria = dados[dados['Categoria'] == categoria]
    else:
        df_categoria = dados

    # Exibindo a tabela
    st.dataframe(df_categoria)

    # Mostrando a quantidade de linhas
    st.write(f'Número de linhas: {len(df_categoria)}')

# Função para mostrar a quantidade de linhas (opcional)
def mostra_qntd_linhas(df):
    st.write(f'Número de linhas: {len(df)}')

# função para selecionar a quantidade de linhas do dataframe
def mostra_qntd_linhas(dataframe):

    qntd_linhas = st.sidebar.slider('Selecione a quantidade de linhas que deseja mostrar na tabela', min_value = 1, max_value = len(dataframe), step = 1)

    st.write(dataframe.head(qntd_linhas).style.format(subset = ['Valor'], formatter="{:.2f}"))
